---
title: "Coinbase Pitch"
output: pdf_document
---

# Intuitive (Fundamental) Valuation

## How the business works
At a high level, the coinbase revenue is 
Revenue = RetailTransactionVolume * Fees
Transaction fees are 95% of their revenue

Their costs are in line with any other growthy tech business - lots of tech investment to build out the platform and lots of sales and marketing. Nothing out of the ordinary, although they took their positive profits from last year and are heavily investing this year & will have negative profits for the next few quarters. 

## Current Market Pricing
Right now, market pricing is far from fundamentals because it is currently priced as 'BTC Up Or Down', rather than as a function of crypto volumes on the platform. The correlation to BTC price is 0.7, correlation to SPX is about 0.5 over the last year. 

The 2022Q1 earnings report was a heavy "surprise" to the downside because Crypto volumes were down, which compressed the top line. But, the fact that crypto volumes were down YTD was no secret - you can literally just look at BTC volume chart and see that. 

The fact that the crypto market as a whole is going down right now is causing Coinbase to go down as well due to that priced in correlation - they are down something like 70% from the IPO and down ~50% over the past month. But, BTC volumes are up - this is a common thing across almost all markets, when volatilities goes up volumes go up and crypto is no different. 

## Catalyst
One short term, one long term catalyst. 
1. Earnings - they report that revenue is up because volumes are up, causing the price to go up in the short term (but potentially revert in line with btc price)
2. Market Players will Change - right now, a very high % of holders of Coinbase are not 'fundamental' players but rather people looking to be long Crypto as a whole but either cannot or will not invest in spot crypto (e.g. most institutional managers) or ETF's that track the broader crypto and meme stocks (e.g. ARKK innovation fund, the largest owner of coinbase at the moment). Within the next 1-2 years, there will be an increase in fundamental value investor coverage in this space which will make the price converge to be priced in line with volume rather than BTC price. 